fix(ci): errexit

diff --git a/pr-previews/cleanup/action.yml b/pr-previews/cleanup/action.yml
--- a/pr-previews/cleanup/action.yml
+++ b/pr-previews/cleanup/action.yml
@@ -17,6 +17,9 @@ runs:
     - name: Get PR Info
       shell: bash
       run: |
+        # need this to not fail on arithmetic expansions
+        set +o errexit
+
         pkgName=${{ inputs.package }}
         openPRs=${{ inputs.openPRs }}
 
@@ -33,9 +36,6 @@ runs:
         # get the list of the "-pr." published version for the packages
         pkgDetails=$(npm view "${pkgName}" --json)
         echo "before"
-        #echo "${pkgDetails}" | jq -r '.time' | jq -r 'to_entries' | jq --arg jq_oldestDate ${oldestDate} '[.[] | select(.value |.[0:19] +"Z" | fromdateiso8601 > ($jq_oldestDate|tonumber))]' | jq '[.[] | .key]'| grep "\-pr." | tac | sed 's/[,\"]//g'
-        echo "${pkgDetails}" | jq -r '.time' | jq -r 'to_entries' | jq --arg jq_oldestDate ${oldestDate} '[.[] | select(.value |.[0:19] +"Z" | fromdateiso8601 > ($jq_oldestDate|tonumber))]'
-        echo "after"
         prVersions=($(echo "${pkgDetails}" | jq -r '.time' | jq -r 'to_entries' | jq --arg jq_oldestDate ${oldestDate} '[.[] | select(.value |.[0:19] +"Z" | fromdateiso8601 > ($jq_oldestDate|tonumber))]' | jq '[.[] | .key]'| grep "\-pr." | tac | sed 's/[,\"]//g'))
         echo "prVersions:"${prVersions[@]}
         if [[ -z "${prVersions}" ]]; then
