feat(slack): new workflow inputs
Add support for custom payloads and additional 'status' values.

diff --git a/slack-actions/workflow-notification/action.yaml b/slack-actions/workflow-notification/action.yaml
--- a/slack-actions/workflow-notification/action.yaml
+++ b/slack-actions/workflow-notification/action.yaml
@@ -6,20 +6,32 @@ inputs:
     description: The Slack webhook URL.
     required: true
   status:
-    description: The status of the workflow, one of "success" or "failure".
+    description: The status of the workflow. One of 'success', 'failure', 'cancelled', or 'skipped'.
     required: true
   # OPTIONAL INPUTS
+  payload:
+    description: The Slack Block Kit JSON payload to send to Slack. If provided, this input will override all other inputs other than `slack-webhook-url`. https://app.slack.com/block-kit-builder
+    required: false
+    default: ''
   header:
     description: The notification header, as a plain text string. Defaults to the workflow name.
     required: false
   success-message:
     description: The message to display when the workflow is successful. Accepts markdown syntax.
     required: false
-    default: ":large_green_circle: Workflow completed successfully :mario_luigi_dance:"
+    default: ':large_green_circle: Workflow completed successfully :mario_luigi_dance:'
   failure-message:
     description: The message to display when the workflow is successful. Accepts markdown syntax.
     required: false
-    default: ":red_circle: Workflow failed :sad-panda:"
+    default: ':red_circle: Workflow failed :sad-panda:'
+  cancelled-message:
+    description: The message to display when the workflow is cancelled. Accepts markdown syntax.
+    required: false
+    default: ':black_circle: Workflow cancelled'
+  skipped-message:
+    description: The message to display when the workflow is skipped. Accepts markdown syntax.
+    required: false
+    default: ':white_circle: Workflow skipped'
 
 runs:
   using: composite
@@ -32,16 +44,33 @@ runs:
         fallbackBranchName=$(echo "${{ github.ref }}" | cut -c12-)
         shortCommitHash=$(echo "${{ github.sha }}" | cut -c1-7)
 
+        # Determine status message
+        if [[ "${{ inputs.status }}" == 'success' ]]; then
+          statusMessage=$(echo "${{ inputs.success-message }}")
+        elif [[ "${{ inputs.status }}" == 'failure' ]]; then
+          statusMessage=$(echo "${{ inputs.failure-message }}")
+        elif [[ "${{ inputs.status }}" == 'cancelled' ]]; then
+          statusMessage=$(echo "${{ inputs.cancelled-message }}")
+        elif [[ "${{ inputs.status }}" == 'skipped' ]]; then
+          statusMessage=$(echo "${{ inputs.skipped-message }}")
+        else
+          echo "Invalid workflow status: ${{ inputs.status }}"
+          exit 1
+        fi
+
         # Output All Variables
         echo "fallback-branch-name=${fallbackBranchName}" >> $GITHUB_OUTPUT
         echo "short-commit-hash=${shortCommitHash}" >> $GITHUB_OUTPUT
+        echo "status-message=${statusMessage}" >> $GITHUB_OUTPUT
 
         # Echo all variables for debugging
         echo "fallback-branch-name=${fallbackBranchName}"
         echo "short-commit-hash=${shortCommitHash}"
+        echo "status-message=${statusMessage}"
 
     - name: Construct Slack payload
       id: slack-payload
+      if: ${{ inputs.payload == '' }}
       shell: bash
       run: |
         PAYLOAD=$(cat << EOF
@@ -59,7 +88,7 @@ runs:
               "type": "section",
               "text": {
                 "type": "mrkdwn",
-                "text": "${{ inputs.status == 'failure' && inputs.failure-message || inputs.success-message }}"
+                "text": "${{ steps.slack-variables.outputs.status-message }}"
               }
             },
             {
@@ -94,7 +123,7 @@ runs:
                   "text": {
                     "type": "plain_text",
                     "emoji": true,
-                    "text": "${{ inputs.status == 'failure' && 'View failed run' || 'View successful run' }}"
+                    "text": "${{ inputs.status == 'failure' && 'View failed run' || 'View workflow run' }}"
                   }
                 }
               ]
@@ -113,4 +142,4 @@ runs:
         SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
         SLACK_WEBHOOK_TYPE: 'INCOMING_WEBHOOK'
       with:
-        payload: ${{ steps.slack-payload.outputs.payload }}
+        payload: ${{ inputs.payload != '' && inputs.payload || steps.slack-payload.outputs.payload }}
