feat(sca): refactored grype cache (#318)
feat(scan-docker-image): refactored grype cache

BREAKING CHANGE:

- Removes "force_grype_db_update" and "skip_grype_db_cache" input
- Adds "grype_db_cache" and "grype_db_cache_token" input for private grype db mirror
- Grype DB caching strategy: GH Cache -> Grype DB mirror (if specified) -> Grype upstream

diff --git a/security-actions/scan-docker-image/action.yml b/security-actions/scan-docker-image/action.yml
--- a/security-actions/scan-docker-image/action.yml
+++ b/security-actions/scan-docker-image/action.yml
@@ -26,7 +26,7 @@ inputs:
   fail_build:
     description: 'fail the build if the vulnerability is above the severity cutoff'
     required: false
-    default: false
+    default: 'false'
     type: choice
     options:
     - 'true'
@@ -38,30 +38,14 @@ inputs:
   upload-sbom-release-assets:
     description: 'specify to only upload sboms to GH release assets'
     required: false
-    default: false
+    default: 'false'
     type: choice
     options:
     - 'true'
     - 'false'
-  force_grype_db_update:
-    required: false
-    default: false
-    description: 'Force to download DB when cache is available and up-to-date'
-    type: choice
-    options:
-    - 'true'
-    - 'false'
-  skip_grype_db_cache:
-    required: false
-    default: true
-    description: 'Skip grype db caching'
-    type: choice
-    options:
-      - 'true'
-      - 'false'
   skip_cis_scan:
     required: false
-    default: false
+    default: 'false'
     description: 'Toggle to skip Trivy scan'
     type: choice
     options:
@@ -77,6 +61,12 @@ inputs:
     description: 'Specify whether to orient results by CVE rather than GHSA'
     required: false
     default: 'false'
+  grype_db_cache:
+    description: 'GitHub repository containing Grype DB cache (format: owner/repo@ref). Database should be named `db_v*.tar.zst` on the default branch.'
+    required: false
+  grype_db_cache_token:
+    description: 'Token for accessing `grype_db_cache`.'
+    required: false
 
 outputs:
   cis-json-report:
@@ -157,91 +147,113 @@ runs:
           exit 1
         fi
         echo "::endgroup::"
-    
-    - name: Download Grype binary
+
+    # Default Action supported Cache DB is disabled to avoid pulling from upstream and failing if unavailablein Git Cache.
+    # Instead handled explicitly to try from mirror before reaching upstream for more realiability
+    - name: Install Grype
+      id: grype_install
+      uses: anchore/scan-action/download-grype@f6601287cdb1efc985d6b765bbf99cb4c0ac29d8 # v7.0.0
+      with:
+        cache-db: false
+
+    - name: Get Grype version and DB schema installed by Anchore Action
+      id: grype_metadata
       shell: bash
       run: |
-        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin v0.96.1
+        # Set grype executable path from action output
+        grype_cmd=${{ steps.grype_install.outputs.cmd }}
+        grype_version=$($grype_cmd version -o json | jq -r '.version')
+        grype_db_schema=$($grype_cmd version -o json | jq '.supportedDbSchema')
 
-    # Skip Cache Restoration: If skip_grype_db_cache is true, skip the restoration of the cache.
-    # Check for any existing cache to reuse
-    - name: Grype DB Cache
-      id: grype_db_cache
-      if: ${{ inputs.skip_grype_db_cache != 'true' && inputs.force_grype_db_update != 'true' }}
+        echo "grype_cmd=${{ steps.grype_install.outputs.cmd }}" >> $GITHUB_OUTPUT
+        echo "grype_db_schema=${grype_db_schema}" >> $GITHUB_OUTPUT
+        echo "grype_version=${grype_version}" >> $GITHUB_OUTPUT
+
+        echo "::group::Grype version and DB schema"
+        echo "grype_version=${grype_version}"
+        echo "grype_db_schema=${grype_db_schema}"
+        echo "::endgroup::"
+      env:
+        grype: ${{ steps.grype.outputs.grype-path }}
+
+    # Explicitly check for Grype DB in Git Cache
+    - name: Check Git Cache for Grype DB
+      id: grype_db_git_cache
       uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
       with:
         # Grype cache files are stored in `~/.cache/grype/db` on Linux/macOS
         path: ~/.cache/grype/db
         key: |
-          cache_grype_${{ github.run_id }}_${{ github.run_attempt }}
-        restore-keys: |
-          cache_grype_${{ github.run_id }}_
-          cache_grype_db
+          cache_grype_db_v${{ steps.grype_metadata.outputs.grype_db_schema }}
 
-    # Make a network call to anchore grype CDN.
-    # This could fail when CDN is flaky for long periods of time.
-    # Setting timeout for available avoids long stuck grype processes on workflow jobs
+    # Explicitly check for Grype DB in specified mirror
+    - name: Parse Grype DB cache input
+      if: steps.grype_db_git_cache.outputs.cache-hit != 'true' && inputs.grype_db_cache != ''
+      shell: bash
+      id: parse_grype_cache
+      run: |
+        REPO=$(echo "${{ inputs.grype_db_cache }}" | cut -d'@' -f1)
+        REF=$(echo "${{ inputs.grype_db_cache }}" | cut -d'@' -f2)
+        echo "repository=${REPO}" >> $GITHUB_OUTPUT
+        echo "ref=${REF}" >> $GITHUB_OUTPUT
 
-    ## Edgecase: Grype DB will never update if stale cache is found
-    - name: Grype DB Check Updates
-      #if: ${{ steps.cache_grype_db.outputs.cache-hit != 'true' }}
-      id: grype_db
+    - name: Checkout Grype DB cache Repo
+      if: steps.grype_db_git_cache.outputs.cache-hit != 'true' && inputs.grype_db_cache != ''
+      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+      with:
+        repository: ${{ steps.parse_grype_cache.outputs.repository }}
+        ref: ${{ steps.parse_grype_cache.outputs.ref }}
+        path: grype-db-cache
+        token: ${{ inputs.grype_db_cache_token }}
+
+    - name: Setup Grype DB from cache repository
+      if: steps.grype_db_git_cache.outputs.cache-hit != 'true' && inputs.grype_db_cache != ''
       shell: bash
       run: |
-        db_check_status=0
-        db_update_status=0
-        echo "::group::Grype DB Status Check"
-        grype db check -vv || db_check_status=$?
-        if [[ "${db_check_status}" -eq 0 ]]; then
-          echo "::notice ::Grype DB is already up-to-date"
-        fi
+        # Import Grype DB
+        # Expected to be recent and kept up-to-date every 12 hours for specific schema
+        ${{steps.grype_metadata.outputs.grype_cmd}} db import grype-db-cache/db/db_v${{ steps.grype_metadata.outputs.grype_db_schema }}.tar.zst
+        rm -rf grype-db-cache
+
+    # Default: Grype DB update from upstream
+    - name: Grype DB Update from upstream
+      if: steps.grype_db_git_cache.outputs.cache-hit != 'true' && inputs.grype_db_cache == ''
+      id: grype_db_update
+      shell: bash
+      run: |
+        echo "::group::Update Grype DB"
+        ${{steps.grype_metadata.outputs.grype_cmd}} db update -vv || true
         echo "::endgroup::"
 
-        echo "::group::Update Grype DB"
-        if [[ "${db_check_status}" -ne 0 ]] || [[ ${FORCE_GRYPE_DB_UPDATE} == "true" ]]; then
-          grype db update -vv || db_update_status=$?     
-          if [[ "${db_update_status}" -ne 0 ]]; then
-            GRYPE_DB_UPDATE_MSG="Grype DB updates was not successful. SCA / CVE Grype results might be skipped / unavailable due to DB issues"
-            if [[ ${FAIL_BUILD} -eq 1 ]]; then
-              echo "::error ::${GRYPE_DB_UPDATE_MSG}"
-              exit ${FAIL_BUILD}
-            elif [[ $FAIL_BUILD -eq 0 ]]; then
-              echo "::warning ::${GRYPE_DB_UPDATE_MSG}"
-            fi
-          else
-            echo "::notice ::Grype DB is updated succesfully"
+    - name: Check Grype DB Status
+      id: grype_db_status
+      shell: bash
+      run: |
+        echo "::group::Print Grype DB status"
+        db_status=$?
+        ${{steps.grype_metadata.outputs.grype_cmd}} db status || db_status=$?
+        if [[ "${db_status}" -ne 0 ]]; then
+          msg="Grype DB initialization was not successful. CVE results unavailable due to DB issues"
+          if [[ ${FAIL_BUILD} -eq 1 ]]; then
+            echo "::error ::${msg}"
+            exit ${FAIL_BUILD}
+          elif [[ $FAIL_BUILD -eq 0 ]]; then
+            echo "::warning ::${msg}"
           fi
+        else
+          echo "::notice ::Grype DB is updated successfully"
         fi
+        echo "db_status=${db_status}" >> $GITHUB_OUTPUT
         echo "::endgroup::"
-        
-        echo "GRYPE_DB_CHECK_UPDATE_STATUS=${db_check_status}" >> $GITHUB_OUTPUT
-        echo "GRYPE_DB_UPDATE_STATUS=${db_update_status}" >> $GITHUB_OUTPUT
       env:
         FAIL_BUILD: ${{ (steps.meta.outputs.global_enforce_build_failure == 'true' || inputs.fail_build == 'true') && '1' || '0' }}
-        GRYPE_DB_UPDATE_AVAILABLE_TIMEOUT: 30s # timeout to fetch listing.json to check if db download is needed
-        GRYPE_DB_UPDATE_DOWNLOAD_TIMEOUT: 600s # timeout for actual db download if needed
-        FORCE_GRYPE_DB_UPDATE: ${{ inputs.force_grype_db_update }} 
 
-    # Save cache when db update is available (i.e drift) and update is successful
-    # Condition helps When this action is invoked more than once in the same workflow
-    # Example: first workflow saves cache if updates available and second retries to save again even when latest updated cache is available and fails
-    # Skip Cache Saving: If skip_grype_db_cache is true, skip saving the cache updates.
-    - name: Update Cache / Save Grype DB updates
-      if: ${{ inputs.skip_grype_db_cache != 'true' && steps.grype_db.outputs.GRYPE_DB_CHECK_UPDATE_STATUS != 0 && steps.grype_db.outputs.GRYPE_DB_UPDATE_STATUS }}
-      id: save_grype_db_cache_updates
-      uses: actions/cache/save@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
-      with:
-        # Grype cache files are stored in `~/.cache/grype/db` on Linux/macOS
-        path: ~/.cache/grype/db
-        key: |
-          cache_grype_${{ github.run_id }}_${{ github.run_attempt }}
-
-    # Grype is invoked first time ever 
+    # Grype is invoked first time ever
     # Don't fail during report generation
     - name: Vulnerability analysis of SBOM
       uses: anchore/scan-action@f6601287cdb1efc985d6b765bbf99cb4c0ac29d8 # v7.0.0
       id: grype_analysis_sarif
-      if: ${{ steps.sbom_report.outputs.files_exists == 'true' && steps.grype_db_check_updates.outputs.GRYPE_DB_UPDATE_STATUS == 0 }}
+      if: ${{ steps.sbom_report.outputs.files_exists == 'true' && steps.grype_db_status.outputs.db_status == '0' }}
       with:
         sbom: ${{ steps.meta.outputs.sbom_spdx_file }}
         output-format: sarif
@@ -249,6 +261,7 @@ runs:
         add-cpes-if-none: true
         severity-cutoff: ${{ steps.meta.outputs.global_severity_cutoff }}
         by-cve: ${{ inputs.by_cve }}
+        grype-version: ${{ steps.grype_install.outputs.grype_version }}
       env:
         GRYPE_DB_AUTO_UPDATE: false # Use grype db pointed from grype_db step above
 
@@ -257,7 +270,7 @@ runs:
     - name: Vulnerability analysis of SBOM
       uses: anchore/scan-action@f6601287cdb1efc985d6b765bbf99cb4c0ac29d8 # v7.0.0
       id: grype_analysis_json
-      if: ${{ steps.sbom_report.outputs.files_exists == 'true' && steps.grype_db_check_updates.outputs.GRYPE_DB_UPDATE_STATUS == 0 }}
+      if: ${{ steps.sbom_report.outputs.files_exists == 'true' && steps.grype_db_status.outputs.db_status == '0' }}
       with:
         sbom: ${{ steps.meta.outputs.sbom_spdx_file }}
         output-format: json
@@ -265,11 +278,11 @@ runs:
         add-cpes-if-none: true
         severity-cutoff: ${{ steps.meta.outputs.global_severity_cutoff }}
         by-cve: ${{ inputs.by_cve }}
+        grype-version: ${{ steps.grype_install.outputs.grype_version }}
       env:
         GRYPE_DB_AUTO_UPDATE: false # Use grype db pointed from grype_db step above
 
     - name: Check vulnerability analysis report existence
-      if: ${{ steps.grype_db_check_updates.outputs.GRYPE_DB_UPDATE_STATUS == 0 }}
       id: grype_report
       shell: bash
       run: |
@@ -289,14 +302,12 @@ runs:
     # Grype CVE Action generates an ./results.sarif or ./results.report and no way to customize output file name
     # Hack to increase readability of grype artifacts attached to workflows and releases
     - name: Rename grype analysis report
-      if: ${{ steps.grype_db_check_updates.outputs.GRYPE_DB_UPDATE_STATUS == 0 }} # Run only if DB is available on the runner
       shell: bash
       run: |
         mv ${{ steps.grype_analysis_sarif.outputs.sarif }} ${{ steps.meta.outputs.grype_sarif_file }}
         mv ${{ steps.grype_analysis_json.outputs.json }} ${{ steps.meta.outputs.grype_json_file }}
 
     - name: Upload grype analysis report
-      if: ${{ steps.grype_db_check_updates.outputs.GRYPE_DB_UPDATE_STATUS == 0 }} # Run only if DB is available on the runner
       uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
       with:
         name: ${{ steps.meta.outputs.grype_sarif_file }}
@@ -306,7 +317,6 @@ runs:
 
     # Upload grype cve reports
     - name: Upload grype analysis report
-      if: ${{ steps.grype_db_check_updates.outputs.GRYPE_DB_UPDATE_STATUS == 0 }} # Run only if DB is available on the runner
       uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
       with:
         name: ${{ steps.meta.outputs.grype_json_file }}
@@ -319,7 +329,7 @@ runs:
     # Table format will supress any specified ignore rules
     - name: Inspect Vulnerability analysis of SBOM
       uses: anchore/scan-action@f6601287cdb1efc985d6b765bbf99cb4c0ac29d8 # v7.0.0
-      if: ${{ steps.sbom_report.outputs.files_exists == 'true' && steps.grype_db_check_updates.outputs.GRYPE_DB_UPDATE_STATUS == 0  }}
+      if: ${{ steps.sbom_report.outputs.files_exists == 'true' && steps.grype_db_status.outputs.db_status == '0' }}
       with:
         sbom: ${{ steps.meta.outputs.sbom_spdx_file }}
         output-format: table
@@ -327,6 +337,7 @@ runs:
         add-cpes-if-none: true
         severity-cutoff: ${{ steps.meta.outputs.global_severity_cutoff }}
         by-cve: ${{ inputs.by_cve }}
+        grype-version: ${{ steps.grype_install.outputs.grype_version }}
       env:
         GRYPE_DB_AUTO_UPDATE: false # Use grype db pointed from grype_db step above
 
@@ -345,30 +356,30 @@ runs:
         fi
         echo "::endgroup::"
 
+      # Issue: https://github.com/aquasecurity/trivy/issues/7938
+      # Discussion: https://github.com/aquasecurity/trivy/discussions/7668
+      # Fix: Refer https://github.com/aquasecurity/trivy/discussions/7951 usign mirror.gcr.io
+    - name: Install Trivy
+      shell: bash
+      run: |
+        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.60.0
+
     - name: Parse Trivy DB cache input
       if: inputs.trivy_db_cache != ''
       shell: bash
-      id: parse_cache
+      id: parse_trivy_cache
       run: |
         REPO=$(echo "${{ inputs.trivy_db_cache }}" | cut -d'@' -f1)
         REF=$(echo "${{ inputs.trivy_db_cache }}" | cut -d'@' -f2)
         echo "repository=${REPO}" >> $GITHUB_OUTPUT
         echo "ref=${REF}" >> $GITHUB_OUTPUT
 
-      # Issue: https://github.com/aquasecurity/trivy/issues/7938
-      # Discussion: https://github.com/aquasecurity/trivy/discussions/7668
-      # Fix: Refer https://github.com/aquasecurity/trivy/discussions/7951 usign mirror.gcr.io 
-    - name: Install Trivy
-      shell: bash
-      run: |
-        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.60.0
-
     - name: Checkout Trivy DB cache
       if: inputs.trivy_db_cache != ''
       uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
       with:
-        repository: ${{ steps.parse_cache.outputs.repository }}
-        ref: ${{ steps.parse_cache.outputs.ref }}
+        repository: ${{ steps.parse_trivy_cache.outputs.repository }}
+        ref: ${{ steps.parse_trivy_cache.outputs.ref }}
         path: trivy-db-cache
         token: ${{ inputs.trivy_db_cache_token }}
 
@@ -378,7 +389,7 @@ runs:
       run: |
         # Create Trivy cache directory
         mkdir -p ~/.cache/trivy/db
-        
+
         # Extract the DB
         cd trivy-db-cache
         tar -xvf db.tar.gz -C ~/.cache/trivy/db
@@ -386,7 +397,7 @@ runs:
         rm -rf trivy-db-cache
 
     # Issue: https://github.com/aquasecurity/trivy/issues/7938
-    # Fix: Refer https://github.com/aquasecurity/trivy/discussions/7951 usign mirror.gcr.io 
+    # Fix: Refer https://github.com/aquasecurity/trivy/discussions/7951 usign mirror.gcr.io
     - name: Generate docker-cis JSON report
       if: ${{ inputs.skip_cis_scan != 'true' && steps.meta.outputs.scan_image != '' }}
       id: cis_json
